use-color=true
show-battery=true
show-memory=true
shell_version=false
speed_type=raw
speed_shorthand=false
memory_percent=no
package_managers=pacman,apt
distro_shorthand=off
os_arch=true
image_backend=w3m
image_source=auto
ascii_colors=(distro)
bold_enabled=on
color_blocks=on
block_range=(0 15)
block_width=3
block_color_maps=
gap=3
vertical_separator=no
stdout=false
