# Nordic neofetch config
# https://github.com/dylanaraps/neofetch/wiki/Customizing-Info

print_info() {
    info title
    info underline

    info "OS" distro
    info "Host" model
    info "Kernel" kernel
    info "Uptime" uptime
    info "Packages" packages
    info "Shell" shell
    info "Terminal" term
    info "CPU" cpu
    info "Memory" memory

    colors
    lines
}

title_fqdn=
kernel_shorthand=on
distro_shorthand=off
os_arch=true
uptime_shorthand=tiny
memory_percent=no
package_managers=pacman,apt
shell_version=
speed_type=raw
speed_shorthand=no
bold_enabled=on
color_blocks=on
block_range=(0 15)
block_width=3
block_color_maps=
gap=3
vertical_separator=no
image_backend=
image_source=
ascii_colors=(distro)
ascii_distro=auto
